name: React CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4

    - name: Configurar Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Instalar dependências
      run: npm install

    - name: Fazer build do projeto
      run: npm run build
      
    - name: Upload do build como artefato
      uses: actions/upload-artifact@v4
      with:
        name: react-app-build
        path: build/
    
    - name: Criar Release no GitHub
      if: startsWith (github.ref,'refs/tags/')
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        body: "Release gerada automaticamente para a tag ${{ github.ref_name }}"
        draft: false
        prerelease: false
        files: |
          build/**/*
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
